In [3]:
import os
import pandas as pd
import sys
sys.path.append(os.path.abspath(os.path.join(".."))) 
from src.technical_indicators import TechnicalIndicatorAnalyzer

stock_files = [
    "../data/yfinance/AAPL_historical_data.csv",
    "../data/yfinance/AMZN_historical_data.csv",
    "../data/yfinance/GOOG_historical_data.csv",
    "../data/yfinance/META_historical_data.csv",

    "../data/yfinance/MSFT_historical_data.csv",
    
    "../data/yfinance/NVDA_historical_data.csv", 
    "../data/yfinance/TSLA_historical_data.csv",
]

all_data = {}

for file in stock_files:
    print(f"Processing {file}")
    indicator = TechnicalIndicatorAnalyzer(file)
    df_with_indicators = indicator.get_indicated_data()
    all_data[file] = df_with_indicators
    display(df_with_indicators.tail(3))  # Show last few rows

Processing ../data/yfinance/AAPL_historical_data.csv

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,SMA_20,SMA_50,RSI,MACD,MACD_Signal,MACD_Hist
Date,,,,,,,,,,,,,,
2024-07-26,218.699997,219.490005,216.009995,217.960007,217.708008,41601300,0.0,0.0,224.633500,209.7090,48.055700,3.026267,5.479431,-2.453164
2024-07-29,216.960007,219.300003,215.750000,218.240005,217.987686,36311800,0.0,0.0,225.014500,210.2794,48.476184,2.448591,4.873263,-2.424672
2024-07-30,219.190002,220.330002,216.119995,218.800003,218.547043,41643800,0.0,0.0,225.117001,210.8586,49.359115,2.012764,4.301163,-2.288399

Processing ../data/yfinance/AMZN_historical_data.csv

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,SMA_20,SMA_50,RSI,MACD,MACD_Signal,MACD_Hist
Date,,,,,,,,,,,,,,
2024-07-26,180.389999,183.190002,180.240005,182.500000,182.500000,29506000,0.0,0.0,191.4345,187.1382,41.146719,-2.065994,-0.307283,-1.758711
2024-07-29,183.839996,184.750000,182.380005,183.199997,183.199997,33270100,0.0,0.0,190.9320,187.0824,42.432437,-2.133520,-0.672530,-1.460990
2024-07-30,184.720001,185.860001,179.380005,181.710007,181.710007,39508600,0.0,0.0,190.1575,187.0440,40.408843,-2.280971,-0.994218,-1.286753

Processing ../data/yfinance/GOOG_historical_data.csv

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,SMA_20,SMA_50,RSI,MACD,MACD_Signal,MACD_Hist
Date,,,,,,,,,,,,,,
2024-07-26,168.770004,169.839996,165.865005,168.679993,168.679993,25150100,0.0,0.0,183.780501,180.2950,31.843937,-1.972672,0.433845,-2.406517
2024-07-29,170.500000,172.160004,169.720001,171.130005,171.130005,13768900,0.0,0.0,183.166001,180.2400,36.545844,-2.433223,-0.139569,-2.293654
2024-07-30,171.830002,172.949997,170.119995,171.860001,171.860001,13681400,0.0,0.0,182.534501,180.1686,37.920068,-2.708091,-0.653273,-2.054818

Processing ../data/yfinance/META_historical_data.csv

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,SMA_20,SMA_50,RSI,MACD,MACD_Signal,MACD_Hist
Date,,,,,,,,,,,,,,
2024-07-26,464.200012,469.769989,459.420013,465.700012,465.700012,14222400,0.0,0.0,496.545000,491.984200,40.628601,-9.500635,-4.125446,-5.375189
2024-07-29,469.880005,473.959991,465.019989,465.709991,465.709991,11339600,0.0,0.0,494.619499,491.667599,40.633231,-9.932081,-5.286773,-4.645308
2024-07-30,467.000000,472.730011,456.700012,463.190002,463.190002,11390400,0.0,0.0,492.545000,491.466799,39.789373,-10.357947,-6.301008,-4.056939

Processing ../data/yfinance/MSFT_historical_data.csv

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,SMA_20,SMA_50,RSI,MACD,MACD_Signal,MACD_Hist
Date,,,,,,,,,,,,,,
2024-07-26,418.200012,428.920013,417.269989,425.269989,424.504852,23583800,0.0,0.0,448.820497,439.071799,37.944660,-3.771598,0.735855,-4.507452
2024-07-29,431.579987,432.149994,424.700012,426.730011,425.962250,15125800,0.0,0.0,447.809497,439.144800,39.217239,-4.420024,-0.295321,-4.124703
2024-07-30,427.720001,429.049988,417.359985,422.920013,422.159119,32687600,0.0,0.0,446.118997,439.183400,37.080269,-5.181612,-1.272579,-3.909033

Processing ../data/yfinance/NVDA_historical_data.csv

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,SMA_20,SMA_50,RSI,MACD,MACD_Signal,MACD_Hist
Date,,,,,,,,,,,,,,
2024-07-26,116.190002,116.199997,111.580002,113.059998,113.059998,293399100,0.0,0.0,123.6640,118.85288,40.940507,-1.381013,0.795656,-2.176669
2024-07-29,113.690002,116.279999,111.300003,111.589996,111.589996,248152100,0.0,0.0,123.0665,119.19208,39.606589,-1.923793,0.251767,-2.175559
2024-07-30,111.519997,111.989998,102.540001,103.730003,103.730003,486833300,0.0,0.0,122.0380,119.37950,33.349720,-2.954132,-0.389413,-2.564719

Processing ../data/yfinance/TSLA_historical_data.csv

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,SMA_20,SMA_50,RSI,MACD,MACD_Signal,MACD_Hist
Date,,,,,,,,,,,,,,
2024-07-26,221.190002,222.279999,215.330002,219.800003,219.800003,94604100,0.0,0.0,240.238,203.9960,46.752165,7.302106,13.116159,-5.814053
2024-07-29,224.899994,234.270004,224.699997,232.100006,232.100006,129201800,0.0,0.0,241.949,205.1582,52.664511,6.593101,11.811547,-5.218447
2024-07-30,232.250000,232.410004,220.000000,222.619995,222.619995,100560300,0.0,0.0,242.587,206.1138,48.220474,5.206237,10.490485,-5.284248